
server:
  port: 8081
  servlet:

spring:
  config:
    activate:
      on-profile:
        - prod


  cache:
    type: redis
  redis:

    host: 127.0.0.1
    port: 6397

    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5

  security:
    user:
      name: java
      password: 1234

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testdb #?????? ?????.
    username: kang
    password:


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #        format_sql: true
        default_batch_fetch_size: 100




decorator:
  datasource:
    p6spy:
      enable-logging: true


cloud:
  aws:
    credentials:
      instanceProfile: true #AWS의 instanceProfile를 사용
    region:
      static: ap-northeast-2
    s3:
      bucket: kanglog-bucket
    stack:
      auto: false